on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        cache: true
        cache-dependency-path: "./src/packages.lock.json"
        
    - name: Restore dependencies
      run: dotnet restore --use-lock-file
      working-directory: src
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: src
      
    - name: Pull Ollama Docker image
      run: docker pull ollama/ollama:latest
      
    - name: Load Docker volume from cache
      id: load-cache
      uses: actions/cache@v3
      with:
        path: /root/.ollama
        key: ollama-volume-${{ github.sha }}
        restore-keys: |
          ollama-volume-
      
    - name: Run Ollama server container
      run: docker run -d -v /root/.ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama:latest

    - name: Load qwen:0.5b model into Ollama server
      run: docker exec ollama ollama run qwen:0.5b
      if: steps.load-cache.outputs.cache-hit != 'true'
        
    - name: Run integration tests
      run: dotnet test --no-build --verbosity normal
      working-directory: tests/OllamaClientLibrary.IntegrationTests
      
    - name: Stop Ollama container
      run: docker stop ollama
      
    - name: Save Docker volume to cache
      uses: actions/cache@v3
      with:
        path: /root/.ollama
        key: ollama-volume-${{ github.sha }}

  codeql:
    name: "CodeQL"
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      matrix:
        language: [ 'csharp' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        cache: true
        cache-dependency-path: "./src/packages.lock.json"
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
    - name: Autobuild
      uses: github/codeql-action/autobuild@v3
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
