name: CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - uses: actions/checkout@v4
    
    # Step 2: Set up .NET (for C# projects)
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x # or whichever version your project uses
        cache: true
        cache-dependency-path: "./src/packages.lock.json"
        
    # Step 3: Restore dependencies for the C# project
    - name: Restore dependencies
      run: dotnet restore --use-lock-file
      working-directory: src
      
    # Step 4: Build the C# project
    - name: Build
      run: dotnet build --no-restore
      working-directory: src
      
    # Step 5: Install Ollama with the llama3.2:1b model
    - name: Install Ollama (via Docker) with llama3.2:1b model
      run: |
        docker pull ollama/ollama:latest  # Pull latest Ollama image
        docker run --rm -d --name ollama-server -p 11434:11434 ollama/ollama:latest /bin/bash -c "ollama model load llama3.2:1b"
        
    # Step 6: Run the integration tests
    - name: Run integration tests
      run: dotnet test --no-build --verbosity normal
      working-directory: tests/OllamaClientLibrary.IntegrationTests

  codeql:
    name: "CodeQL"
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      matrix:
        language: [ 'csharp' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        cache: true
        cache-dependency-path: "./src/packages.lock.json"
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
    - name: Autobuild
      uses: github/codeql-action/autobuild@v3
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
